language: java

addons:
  chrome: stable

install:
  - export latest=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
  - curl -s https://chromedriver.storage.googleapis.com/${latest}/chromedriver_linux64.zip -O
  - unzip -q -o chromedriver_linux64.zip
  - which chromedriver_linux64
  #- wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  #- unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.12/bin/
  #- export CHROME_BIN=chromium-browser
  #- chromedriver-update

  - #install things from pom

script:
  - mvn -Dtest=LoginTests test -Dwebdriver.chrome.driver=$(which chromedriver_linux64) -Dbrowser="headless" 
