language: java

addons:
  chrome: stable

install:
  #- wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  #- unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.12/bin/
  #- export CHROME_BIN=chromium-browser
  - chromedriver-update

  - #install things from pom

script:
  - mvn -Dtest=LoginTests test -Dbrowser="headless"
